---
apiVersion: v1
kind: Namespace
metadata:
  name: apollo-workers
  labels:
    name: apollo-workers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apollo-coordinator
  namespace: apollo-workers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coordinator-role
  namespace: apollo-workers
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coordinator-role-binding
  namespace: apollo-workers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coordinator-role
subjects:
  - namespace: apollo-workers
    kind: ServiceAccount
    name: apollo-coordinator
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apollo-intermediate-files-pvc
  namespace: apollo-workers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: apollo-workers
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 4750
  selector:
    app: coordinator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
  namespace: apollo-workers
spec:
  selector:
    matchLabels:
      app: coordinator
  serviceName: coordinator
  replicas: 1
  template:
    metadata:
      namespace: apollo-workers
      labels:
        app: coordinator
    spec:
      serviceAccountName: apollo-coordinator
      containers:
        - name: coordinator
          image: localhost:5000/apollo:coordinator
          imagePullPolicy: Always
          ports:
            - containerPort: 4750
          volumeMounts:
            - name: data
              mountPath: /apollo/data
            - name: artifacts
              mountPath: /coordinator/artifacts
          env:
            - name: COORDINATOR_OPTS
              value: "--trace"
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: apollo-workers
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: artifacts
        namespace: apollo-workers
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
    

  